version: 2

formats:
  - pdf
  - epub

sphinx:
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - python -m invoke rtd-pre-build

   configuration: docs/source/conf.py

python:
   install:
   - requirements: requirements-dev.txt
