version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - python -m invoke check-docs-image-ext
      - python -m invoke localize-resources

sphinx:
   configuration: docs/source/conf.py

python:
   install:
   - requirements: requirements-dev.txt