version: 2

#formats:
#  - pdf
#  - epub

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - python -m invoke rtd-pre-build

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements-dev.txt
