services:
  qgis-testing-environment:
    build:
      context: .
      dockerfile: docker/test.Dockerfile
      args:
        IMAGE: "${IMAGE}"
        QGIS_VERSION_TAG: "${QGIS_VERSION_TAG}"
    image: trends-earth-qgis-test:${QGIS_VERSION_TAG}
    pull_policy: build
    volumes:
      - ./:/tests_directory
    environment:
      QGIS_VERSION_TAG: "${QGIS_VERSION_TAG}"
      WITH_PYTHON_PEP: "${WITH_PYTHON_PEP}"
      ON_TRAVIS: "${ON_TRAVIS}"
      MUTE_LOGS: "${MUTE_LOGS}"
      PIP_BREAK_SYSTEM_PACKAGES: "1"
      QT_QPA_PLATFORM: "offscreen"
      QTWEBENGINE_DISABLE_SANDBOX: "1"
      DISPLAY: ":99"
      TE_E2E_CLIENT_ID: "${TE_E2E_CLIENT_ID:-}"
      TE_E2E_CLIENT_SECRET: "${TE_E2E_CLIENT_SECRET:-}"
      TE_E2E_API_URL: "${TE_E2E_API_URL:-}"
      TE_E2E_COUNTRIES: "${TE_E2E_COUNTRIES:-}"
      TE_E2E_TIMEOUT_MIN: "${TE_E2E_TIMEOUT_MIN:-}"
      TE_E2E_POLL_SEC: "${TE_E2E_POLL_SEC:-}"
      TE_E2E_LOCAL_TIMEOUT_MIN: "${TE_E2E_LOCAL_TIMEOUT_MIN:-}"
      TE_E2E_OUTPUT_DIR: "${TE_E2E_OUTPUT_DIR:-}"
    working_dir: /tests_directory
    entrypoint: /tests_directory/docker/qgis-testing-entrypoint.sh
    # Enable "command:" line below to immediately run unittests upon docker-compose up
    # command: qgis_testrunner.sh test_suite.test_package
    # Default behaviour of the container is to standby
    command: tail -f /dev/null
    # qgis_testrunner.sh needs tty for tee
    tty: true
