[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "trends.earth"
description = "Analyze land change in support of sustainable land management"
authors = [
    {name = "Conservation International", email = "trends.earth@conservation.org"}
]
readme = "README.md"
requires-python = ">=3.10"
license = {text = "GPL-2.0"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dynamic = ["version"]

[tool.setuptools]
packages = ["LDMP"]

[tool.setuptools-scm]
# Enable setuptools-scm for version management from git tags
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
write_to = "LDMP/_version.py"
write_to_template = """
# This file is auto-generated by setuptools-scm at build time
# Do not edit this file manually
__version__ = "{version}"
__version_tuple__ = {version_tuple}

# Git information captured at build time
# These values are set by the build process in tasks.py
__git_sha__ = "unknown"
__git_date__ = "unknown"
"""

[tool.setuptools-scm.parse_pattern_1]
# Pattern for parsing version tags (e.g., v2.1.18, 2.1.18)
pattern = "^(?:v)?(?P<version>[0-9]+(?:\\.[0-9]+)+)(?:-(?P<prerelease>[a-z]+))?$"
