"""
/***************************************************************************
 LDMP - A QGIS plugin
 This plugin supports monitoring and reporting of land degradation to the UNCCD
 and in support of the SDG Land Degradation Neutrality (LDN) target.
                              -------------------
        begin                : 2017-05-23
        git sha              : $Format:%H$
        copyright            : (C) 2017 by Conservation International
        email                : trends.earth@conservation.org
 ***************************************************************************/
"""

from qgis.PyQt.QtCore import QCoreApplication


class tr_layers:
    def tr(message):
        return QCoreApplication.translate("tr_layers", message)


style_text_dict = {
    # WePlan-Forests (STAC)
    "weplan_available_areas_title": tr_layers.tr("WePlan - {asset_title}"),
    "weplan_available_areas_0": tr_layers.tr("0%"),
    "weplan_available_areas_100": tr_layers.tr("100%"),
    "weplan_restoration_priority_title": tr_layers.tr("WePlan - {asset_title}"),
    "weplan_restoration_priority_0": tr_layers.tr("0%"),
    "weplan_restoration_priority_25": tr_layers.tr("25%"),
    "weplan_restoration_priority_50": tr_layers.tr("50%"),
    "weplan_restoration_priority_75": tr_layers.tr("75%"),
    "weplan_restoration_priority_100": tr_layers.tr("100%"),
    # Nature Map (STAC)
    "naturemap_restoration_priority_title": tr_layers.tr("Nature Map - {asset_title}"),
    "naturemap_restoration_priority_1": tr_layers.tr("Top 5%"),
    "naturemap_restoration_priority_2": tr_layers.tr("10%"),
    "naturemap_restoration_priority_3": tr_layers.tr("15%"),
    "naturemap_restoration_priority_4": tr_layers.tr("20%"),
    "naturemap_restoration_priority_6": tr_layers.tr("30%"),
    "naturemap_restoration_priority_8": tr_layers.tr("40%"),
    "naturemap_restoration_priority_11": tr_layers.tr("55%"),
    "naturemap_restoration_priority_14": tr_layers.tr("70%"),
    "naturemap_restoration_priority_17": tr_layers.tr("85%"),
    "naturemap_restoration_priority_20": tr_layers.tr("100%"),
    # World Terrestrial Ecosystems (STAC)
    "wte_title": tr_layers.tr("World Terrestrial Ecosystems"),
    "wte_1": tr_layers.tr("Polar Moist Sparsley or Non vegetated on Plains"),
    "wte_2": tr_layers.tr("Polar Moist Snow and Ice on Plains"),
    "wte_3": tr_layers.tr("Polar Dry Snow and Ice on Mountains"),
    "wte_4": tr_layers.tr("Polar Dry Sparsley or Non vegetated on Mountains"),
    "wte_5": tr_layers.tr("Polar Moist Sparsley or Non vegetated on Mountains"),
    "wte_6": tr_layers.tr("Polar Moist Snow and Ice on Mountains"),
    "wte_7": tr_layers.tr("Polar Dry Sparsley or Non vegetated on Tablelands"),
    "wte_8": tr_layers.tr("Polar Dry Snow and Ice on Tablelands"),
    "wte_9": tr_layers.tr("Polar Dry Snow and Ice on Plains"),
    "wte_10": tr_layers.tr("Polar Moist Sparsley or Non vegetated on Tablelands"),
    "wte_11": tr_layers.tr("Polar Moist Snow and Ice on Tablelands"),
    "wte_12": tr_layers.tr("Polar Dry Sparsley or Non vegetated on Hills"),
    "wte_13": tr_layers.tr("Polar Dry Snow and Ice on Hills"),
    "wte_14": tr_layers.tr("Polar Dry Sparsley or Non vegetated on Plains"),
    "wte_15": tr_layers.tr("Polar Moist Snow and Ice on Hills"),
    "wte_16": tr_layers.tr("Polar Moist Sparsley or Non vegetated on Hills"),
    "wte_17": tr_layers.tr("Polar Dry Grassland on Mountains"),
    "wte_18": tr_layers.tr("Polar Moist Grassland on Mountains"),
    "wte_19": tr_layers.tr("Polar Moist Shrubland on Plains"),
    "wte_20": tr_layers.tr("Polar Moist Shrubland on Hills"),
    "wte_21": tr_layers.tr("Polar Moist Grassland on Hills"),
    "wte_22": tr_layers.tr("Polar Moist Grassland on Plains"),
    "wte_23": tr_layers.tr("Polar Dry Grassland on Hills"),
    "wte_24": tr_layers.tr("Polar Moist Shrubland on Tablelands"),
    "wte_25": tr_layers.tr("Polar Moist Shrubland on Mountains"),
    "wte_26": tr_layers.tr("Polar Moist Grassland on Tablelands"),
    "wte_27": tr_layers.tr("Polar Moist Forest on Plains"),
    "wte_28": tr_layers.tr("Polar Moist Forest on Hills"),
    "wte_29": tr_layers.tr("Polar Moist Forest on Mountains"),
    "wte_30": tr_layers.tr("Polar Moist Forest on Tablelands"),
    "wte_31": tr_layers.tr("Polar Dry Grassland on Plains"),
    "wte_32": tr_layers.tr("Polar Dry Shrubland on Hills"),
    "wte_33": tr_layers.tr("Polar Moist Settlement on Mountains"),
    "wte_34": tr_layers.tr("Polar Dry Shrubland on Plains"),
    "wte_35": tr_layers.tr("Polar Dry Shrubland on Tablelands"),
    "wte_36": tr_layers.tr("Polar Dry Forest on Plains"),
    "wte_37": tr_layers.tr("Polar Moist Cropland on Hills"),
    "wte_38": tr_layers.tr("Polar Dry Grassland on Tablelands"),
    "wte_39": tr_layers.tr("Polar Moist Cropland on Mountains"),
    "wte_40": tr_layers.tr("Polar Moist Cropland on Plains"),
    "wte_41": tr_layers.tr("Polar Dry Shrubland on Mountains"),
    "wte_42": tr_layers.tr("Polar Moist Cropland on Tablelands"),
    "wte_43": tr_layers.tr("Polar Dry Forest on Hills"),
    "wte_44": tr_layers.tr("Polar Dry Forest on Tablelands"),
    "wte_45": tr_layers.tr("Boreal Moist Sparsley or Non vegetated on Plains"),
    "wte_46": tr_layers.tr("Boreal Moist Grassland on Plains"),
    "wte_47": tr_layers.tr("Boreal Moist Sparsley or Non vegetated on Hills"),
    "wte_48": tr_layers.tr("Boreal Moist Grassland on Hills"),
    "wte_49": tr_layers.tr("Boreal Moist Shrubland on Hills"),
    "wte_50": tr_layers.tr("Boreal Moist Forest on Hills"),
    "wte_51": tr_layers.tr("Boreal Moist Sparsley or Non vegetated on Mountains"),
    "wte_52": tr_layers.tr("Boreal Moist Shrubland on Plains"),
    "wte_53": tr_layers.tr("Boreal Moist Forest on Plains"),
    "wte_54": tr_layers.tr("Boreal Moist Shrubland on Mountains"),
    "wte_55": tr_layers.tr("Boreal Moist Forest on Mountains"),
    "wte_56": tr_layers.tr("Boreal Moist Grassland on Mountains"),
    "wte_57": tr_layers.tr("Boreal Moist Sparsley or Non vegetated on Tablelands"),
    "wte_58": tr_layers.tr("Boreal Moist Shrubland on Tablelands"),
    "wte_59": tr_layers.tr("Boreal Moist Grassland on Tablelands"),
    "wte_60": tr_layers.tr("Boreal Moist Cropland on Hills"),
    "wte_61": tr_layers.tr("Polar Dry Cropland on Plains"),
    "wte_62": tr_layers.tr("Boreal Moist Cropland on Plains"),
    "wte_63": tr_layers.tr("Boreal Moist Forest on Tablelands"),
    "wte_64": tr_layers.tr("Polar Moist Settlement on Plains"),
    "wte_65": tr_layers.tr("Polar Dry Forest on Mountains"),
    "wte_66": tr_layers.tr("Boreal Dry Sparsley or Non vegetated on Plains"),
    "wte_67": tr_layers.tr("Boreal Moist Cropland on Mountains"),
    "wte_68": tr_layers.tr("Boreal Dry Forest on Plains"),
    "wte_69": tr_layers.tr("Boreal Dry Shrubland on Plains"),
    "wte_70": tr_layers.tr("Boreal Dry Sparsley or Non vegetated on Hills"),
    "wte_71": tr_layers.tr("Boreal Dry Shrubland on Hills"),
    "wte_72": tr_layers.tr("Boreal Dry Forest on Hills"),
    "wte_73": tr_layers.tr("Boreal Moist Cropland on Tablelands"),
    "wte_74": tr_layers.tr("Boreal Dry Grassland on Hills"),
    "wte_75": tr_layers.tr("Boreal Dry Grassland on Plains"),
    "wte_76": tr_layers.tr("Polar Dry Cropland on Hills"),
    "wte_77": tr_layers.tr("Boreal Dry Cropland on Plains"),
    "wte_78": tr_layers.tr("Boreal Dry Sparsley or Non vegetated on Tablelands"),
    "wte_79": tr_layers.tr("Polar Dry Cropland on Mountains"),
    "wte_80": tr_layers.tr("Polar Dry Cropland on Tablelands"),
    "wte_81": tr_layers.tr("Boreal Dry Shrubland on Tablelands"),
    "wte_82": tr_layers.tr("Boreal Dry Forest on Tablelands"),
    "wte_83": tr_layers.tr("Boreal Dry Grassland on Tablelands"),
    "wte_84": tr_layers.tr("Boreal Dry Settlement on Plains"),
    "wte_85": tr_layers.tr("Boreal Dry Cropland on Hills"),
    "wte_86": tr_layers.tr("Boreal Moist Settlement on Plains"),
    "wte_87": tr_layers.tr("Boreal Moist Settlement on Hills"),
    "wte_88": tr_layers.tr("Boreal Dry Sparsley or Non vegetated on Mountains"),
    "wte_89": tr_layers.tr("Boreal Dry Grassland on Mountains"),
    "wte_90": tr_layers.tr("Boreal Dry Forest on Mountains"),
    "wte_91": tr_layers.tr("Boreal Dry Cropland on Tablelands"),
    "wte_92": tr_layers.tr("Boreal Dry Shrubland on Mountains"),
    "wte_93": tr_layers.tr("Boreal Dry Cropland on Mountains"),
    "wte_94": tr_layers.tr("Boreal Moist Settlement on Tablelands"),
    "wte_95": tr_layers.tr("Polar Dry Settlement on Plains"),
    "wte_96": tr_layers.tr("Cool Temperate Moist Shrubland on Mountains"),
    "wte_97": tr_layers.tr("Cool Temperate Moist Forest on Mountains"),
    "wte_98": tr_layers.tr("Cool Temperate Moist Sparsley or Non vegetated on Mountains"),
    "wte_99": tr_layers.tr("Cool Temperate Moist Sparsley or Non vegetated on Tablelands"),
    "wte_100": tr_layers.tr("Cool Temperate Moist Shrubland on Tablelands"),
    "wte_101": tr_layers.tr("Cool Temperate Moist Forest on Tablelands"),
    "wte_102": tr_layers.tr("Cool Temperate Moist Cropland on Tablelands"),
    "wte_103": tr_layers.tr("Cool Temperate Moist Cropland on Mountains"),
    "wte_104": tr_layers.tr("Cool Temperate Moist Sparsley or Non vegetated on Hills"),
    "wte_105": tr_layers.tr("Cool Temperate Moist Forest on Hills"),
    "wte_106": tr_layers.tr("Cool Temperate Moist Shrubland on Hills"),
    "wte_107": tr_layers.tr("Cool Temperate Moist Grassland on Mountains"),
    "wte_108": tr_layers.tr("Cool Temperate Moist Settlement on Hills"),
    "wte_109": tr_layers.tr("Cool Temperate Moist Grassland on Tablelands"),
    "wte_110": tr_layers.tr("Cool Temperate Moist Cropland on Hills"),
    "wte_111": tr_layers.tr("Cool Temperate Moist Forest on Plains"),
    "wte_112": tr_layers.tr("Cool Temperate Moist Sparsley or Non vegetated on Plains"),
    "wte_113": tr_layers.tr("Cool Temperate Moist Settlement on Mountains"),
    "wte_114": tr_layers.tr("Cool Temperate Moist Grassland on Hills"),
    "wte_115": tr_layers.tr("Cool Temperate Moist Shrubland on Plains"),
    "wte_116": tr_layers.tr("Cool Temperate Moist Cropland on Plains"),
    "wte_117": tr_layers.tr("Boreal Dry Settlement on Hills"),
    "wte_118": tr_layers.tr("Cool Temperate Moist Snow and Ice on Mountains"),
    "wte_119": tr_layers.tr("Polar Dry Settlement on Mountains"),
    "wte_120": tr_layers.tr("Cool Temperate Moist Settlement on Plains"),
    "wte_121": tr_layers.tr("Boreal Moist Settlement on Mountains"),
    "wte_122": tr_layers.tr("Boreal Dry Settlement on Mountains"),
    "wte_123": tr_layers.tr("Boreal Dry Settlement on Tablelands"),
    "wte_124": tr_layers.tr("Boreal Moist Snow and Ice on Mountains"),
    "wte_125": tr_layers.tr("Boreal Moist Snow and Ice on Hills"),
    "wte_126": tr_layers.tr("Boreal Moist Snow and Ice on Plains"),
    "wte_127": tr_layers.tr("Polar Moist Settlement on Hills"),
    "wte_128": tr_layers.tr("Cool Temperate Moist Grassland on Plains"),
    "wte_129": tr_layers.tr("Cool Temperate Moist Settlement on Tablelands"),
    "wte_130": tr_layers.tr("Boreal Dry Snow and Ice on Mountains"),
    "wte_131": tr_layers.tr("Boreal Moist Snow and Ice on Tablelands"),
    "wte_132": tr_layers.tr("Cool Temperate Moist Snow and Ice on Plains"),
    "wte_133": tr_layers.tr("Cool Temperate Moist Snow and Ice on Tablelands"),
    "wte_134": tr_layers.tr("Cool Temperate Moist Snow and Ice on Hills"),
    "wte_135": tr_layers.tr("Cool Temperate Dry Sparsley or Non vegetated on Mountains"),
    "wte_136": tr_layers.tr("Cool Temperate Dry Shrubland on Mountains"),
    "wte_137": tr_layers.tr("Cool Temperate Dry Forest on Mountains"),
    "wte_138": tr_layers.tr("Cool Temperate Dry Forest on Plains"),
    "wte_139": tr_layers.tr("Cool Temperate Dry Forest on Hills"),
    "wte_140": tr_layers.tr("Cool Temperate Dry Forest on Tablelands"),
    "wte_141": tr_layers.tr("Cool Temperate Dry Shrubland on Tablelands"),
    "wte_142": tr_layers.tr("Cool Temperate Dry Grassland on Mountains"),
    "wte_143": tr_layers.tr("Cool Temperate Dry Shrubland on Hills"),
    "wte_144": tr_layers.tr("Cool Temperate Dry Shrubland on Plains"),
    "wte_145": tr_layers.tr("Cool Temperate Dry Cropland on Plains"),
    "wte_146": tr_layers.tr("Cool Temperate Dry Cropland on Hills"),
    "wte_147": tr_layers.tr("Cool Temperate Dry Sparsley or Non vegetated on Hills"),
    "wte_148": tr_layers.tr("Cool Temperate Dry Cropland on Mountains"),
    "wte_149": tr_layers.tr("Cool Temperate Dry Grassland on Hills"),
    "wte_150": tr_layers.tr("Cool Temperate Dry Cropland on Tablelands"),
    "wte_151": tr_layers.tr("Cool Temperate Dry Sparsley or Non vegetated on Plains"),
    "wte_152": tr_layers.tr("Cool Temperate Dry Sparsley or Non vegetated on Tablelands"),
    "wte_153": tr_layers.tr("Cool Temperate Dry Grassland on Plains"),
    "wte_154": tr_layers.tr("Cool Temperate Dry Settlement on Hills"),
    "wte_155": tr_layers.tr("Cool Temperate Dry Settlement on Tablelands"),
    "wte_156": tr_layers.tr("Cool Temperate Dry Grassland on Tablelands"),
    "wte_157": tr_layers.tr("Cool Temperate Dry Settlement on Plains"),
    "wte_158": tr_layers.tr("Cool Temperate Dry Settlement on Mountains"),
    "wte_159": tr_layers.tr("Warm Temperate Moist Grassland on Plains"),
    "wte_160": tr_layers.tr("Warm Temperate Moist Cropland on Plains"),
    "wte_161": tr_layers.tr("Warm Temperate Moist Settlement on Plains"),
    "wte_162": tr_layers.tr("Warm Temperate Moist Sparsley or Non vegetated on Plains"),
    "wte_163": tr_layers.tr("Warm Temperate Moist Forest on Hills"),
    "wte_164": tr_layers.tr("Warm Temperate Moist Grassland on Hills"),
    "wte_165": tr_layers.tr("Warm Temperate Moist Shrubland on Hills"),
    "wte_166": tr_layers.tr("Warm Temperate Moist Forest on Plains"),
    "wte_167": tr_layers.tr("Warm Temperate Moist Shrubland on Plains"),
    "wte_168": tr_layers.tr("Warm Temperate Moist Cropland on Hills"),
    "wte_169": tr_layers.tr("Warm Temperate Moist Settlement on Hills"),
    "wte_170": tr_layers.tr("Warm Temperate Moist Sparsley or Non vegetated on Hills"),
    "wte_171": tr_layers.tr("Warm Temperate Moist Grassland on Mountains"),
    "wte_172": tr_layers.tr("Warm Temperate Moist Settlement on Mountains"),
    "wte_173": tr_layers.tr("Warm Temperate Moist Cropland on Mountains"),
    "wte_174": tr_layers.tr("Warm Temperate Moist Sparsley or Non vegetated on Mountains"),
    "wte_175": tr_layers.tr("Warm Temperate Moist Shrubland on Mountains"),
    "wte_176": tr_layers.tr("Warm Temperate Moist Forest on Mountains"),
    "wte_177": tr_layers.tr("Warm Temperate Moist Settlement on Tablelands"),
    "wte_178": tr_layers.tr("Warm Temperate Moist Cropland on Tablelands"),
    "wte_179": tr_layers.tr("Warm Temperate Moist Grassland on Tablelands"),
    "wte_180": tr_layers.tr("Warm Temperate Moist Forest on Tablelands"),
    "wte_181": tr_layers.tr("Warm Temperate Moist Shrubland on Tablelands"),
    "wte_182": tr_layers.tr("Warm Temperate Moist Sparsley or Non vegetated on Tablelands"),
    "wte_183": tr_layers.tr("Warm Temperate Dry Shrubland on Mountains"),
    "wte_184": tr_layers.tr("Warm Temperate Dry Cropland on Mountains"),
    "wte_185": tr_layers.tr("Warm Temperate Dry Settlement on Mountains"),
    "wte_186": tr_layers.tr("Warm Temperate Dry Grassland on Mountains"),
    "wte_187": tr_layers.tr("Warm Temperate Dry Cropland on Plains"),
    "wte_188": tr_layers.tr("Warm Temperate Dry Settlement on Plains"),
    "wte_189": tr_layers.tr("Warm Temperate Dry Grassland on Plains"),
    "wte_190": tr_layers.tr("Warm Temperate Dry Cropland on Hills"),
    "wte_191": tr_layers.tr("Warm Temperate Dry Settlement on Hills"),
    "wte_192": tr_layers.tr("Warm Temperate Dry Grassland on Hills"),
    "wte_193": tr_layers.tr("Warm Temperate Dry Shrubland on Hills"),
    "wte_194": tr_layers.tr("Warm Temperate Dry Forest on Mountains"),
    "wte_195": tr_layers.tr("Warm Temperate Dry Forest on Plains"),
    "wte_196": tr_layers.tr("Warm Temperate Dry Shrubland on Plains"),
    "wte_197": tr_layers.tr("Warm Temperate Dry Sparsley or Non vegetated on Hills"),
    "wte_198": tr_layers.tr("Warm Temperate Dry Cropland on Tablelands"),
    "wte_199": tr_layers.tr("Warm Temperate Dry Forest on Hills"),
    "wte_200": tr_layers.tr("Warm Temperate Dry Settlement on Tablelands"),
    "wte_201": tr_layers.tr("Warm Temperate Dry Sparsley or Non vegetated on Plains"),
    "wte_202": tr_layers.tr("Warm Temperate Dry Forest on Tablelands"),
    "wte_203": tr_layers.tr("Warm Temperate Dry Shrubland on Tablelands"),
    "wte_204": tr_layers.tr("Warm Temperate Dry Grassland on Tablelands"),
    "wte_205": tr_layers.tr("Warm Temperate Dry Sparsley or Non vegetated on Mountains"),
    "wte_206": tr_layers.tr("Warm Temperate Dry Sparsley or Non vegetated on Tablelands"),
    "wte_207": tr_layers.tr("Cool Temperate Desert Sparsley or Non vegetated on Plains"),
    "wte_208": tr_layers.tr("Cool Temperate Desert Sparsley or Non vegetated on Hills"),
    "wte_209": tr_layers.tr("Cool Temperate Desert Cropland on Plains"),
    "wte_210": tr_layers.tr("Cool Temperate Desert Grassland on Plains"),
    "wte_211": tr_layers.tr("Cool Temperate Desert Cropland on Hills"),
    "wte_212": tr_layers.tr("Cool Temperate Desert Settlement on Plains"),
    "wte_213": tr_layers.tr("Cool Temperate Desert Sparsley or Non vegetated on Mountains"),
    "wte_214": tr_layers.tr("Cool Temperate Desert Grassland on Hills"),
    "wte_215": tr_layers.tr("Cool Temperate Desert Settlement on Hills"),
    "wte_216": tr_layers.tr("Cool Temperate Desert Sparsley or Non vegetated on Tablelands"),
    "wte_217": tr_layers.tr("Cool Temperate Dry Snow and Ice on Mountains"),
    "wte_218": tr_layers.tr("Warm Temperate Desert Sparsley or Non vegetated on Hills"),
    "wte_219": tr_layers.tr("Cool Temperate Desert Grassland on Mountains"),
    "wte_220": tr_layers.tr("Cool Temperate Desert Cropland on Mountains"),
    "wte_221": tr_layers.tr("Warm Temperate Desert Sparsley or Non vegetated on Plains"),
    "wte_222": tr_layers.tr("Cool Temperate Desert Settlement on Mountains"),
    "wte_223": tr_layers.tr("Warm Temperate Desert Sparsley or Non vegetated on Mountains"),
    "wte_224": tr_layers.tr("Warm Temperate Desert Sparsley or Non vegetated on Tablelands"),
    "wte_225": tr_layers.tr("Warm Temperate Desert Settlement on Mountains"),
    "wte_226": tr_layers.tr("Warm Temperate Desert Grassland on Mountains"),
    "wte_227": tr_layers.tr("Warm Temperate Desert Cropland on Mountains"),
    "wte_228": tr_layers.tr("Cool Temperate Desert Grassland on Tablelands"),
    "wte_229": tr_layers.tr("Cool Temperate Desert Cropland on Tablelands"),
    "wte_230": tr_layers.tr("Warm Temperate Desert Grassland on Hills"),
    "wte_231": tr_layers.tr("Warm Temperate Desert Grassland on Plains"),
    "wte_232": tr_layers.tr("Warm Temperate Desert Cropland on Hills"),
    "wte_233": tr_layers.tr("Warm Temperate Desert Cropland on Plains"),
    "wte_234": tr_layers.tr("Warm Temperate Desert Settlement on Plains"),
    "wte_235": tr_layers.tr("Warm Temperate Desert Cropland on Tablelands"),
    "wte_236": tr_layers.tr("Warm Temperate Desert Shrubland on Plains"),
    "wte_237": tr_layers.tr("Warm Temperate Desert Grassland on Tablelands"),
    "wte_238": tr_layers.tr("Warm Temperate Desert Settlement on Tablelands"),
    "wte_239": tr_layers.tr("Warm Temperate Desert Shrubland on Hills"),
    "wte_240": tr_layers.tr("Warm Temperate Desert Settlement on Hills"),
    "wte_241": tr_layers.tr("Warm Temperate Desert Shrubland on Tablelands"),
    "wte_242": tr_layers.tr("Cool Temperate Desert Forest on Plains"),
    "wte_243": tr_layers.tr("Warm Temperate Desert Shrubland on Mountains"),
    "wte_244": tr_layers.tr("Cool Temperate Desert Shrubland on Plains"),
    "wte_245": tr_layers.tr("Cool Temperate Desert Shrubland on Hills"),
    "wte_246": tr_layers.tr("Cool Temperate Desert Shrubland on Mountains"),
    "wte_247": tr_layers.tr("Cool Temperate Desert Settlement on Tablelands"),
    "wte_248": tr_layers.tr("Cool Temperate Desert Shrubland on Tablelands"),
    "wte_249": tr_layers.tr("Warm Temperate Desert Forest on Mountains"),
    "wte_250": tr_layers.tr("Warm Temperate Desert Forest on Hills"),
    "wte_251": tr_layers.tr("Boreal Desert Grassland on Mountains"),
    "wte_252": tr_layers.tr("Boreal Desert Sparsley or Non vegetated on Mountains"),
    "wte_253": tr_layers.tr("Boreal Desert Cropland on Mountains"),
    "wte_254": tr_layers.tr("Polar Desert Grassland on Mountains"),
    "wte_255": tr_layers.tr("Boreal Desert Grassland on Plains"),
    "wte_256": tr_layers.tr("Boreal Desert Cropland on Plains"),
    "wte_257": tr_layers.tr("Boreal Desert Sparsley or Non vegetated on Tablelands"),
    "wte_258": tr_layers.tr("Boreal Desert Grassland on Tablelands"),
    "wte_259": tr_layers.tr("Warm Temperate Desert Forest on Plains"),
    "wte_260": tr_layers.tr("Cool Temperate Desert Forest on Hills"),
    "wte_261": tr_layers.tr("Sub Tropical Moist Shrubland on Mountains"),
    "wte_262": tr_layers.tr("Sub Tropical Moist Forest on Mountains"),
    "wte_263": tr_layers.tr("Sub Tropical Moist Settlement on Hills"),
    "wte_264": tr_layers.tr("Sub Tropical Moist Settlement on Mountains"),
    "wte_265": tr_layers.tr("Sub Tropical Moist Sparsley or Non vegetated on Hills"),
    "wte_266": tr_layers.tr("Sub Tropical Dry Settlement on Mountains"),
    "wte_267": tr_layers.tr("Sub Tropical Moist Cropland on Hills"),
    "wte_268": tr_layers.tr("Sub Tropical Moist Forest on Hills"),
    "wte_269": tr_layers.tr("Sub Tropical Moist Cropland on Mountains"),
    "wte_270": tr_layers.tr("Sub Tropical Moist Sparsley or Non vegetated on Mountains"),
    "wte_271": tr_layers.tr("Sub Tropical Moist Grassland on Mountains"),
    "wte_272": tr_layers.tr("Sub Tropical Dry Cropland on Mountains"),
    "wte_273": tr_layers.tr("Sub Tropical Dry Sparsley or Non vegetated on Mountains"),
    "wte_274": tr_layers.tr("Sub Tropical Dry Forest on Mountains"),
    "wte_275": tr_layers.tr("Sub Tropical Dry Grassland on Mountains"),
    "wte_276": tr_layers.tr("Sub Tropical Dry Settlement on Plains"),
    "wte_277": tr_layers.tr("Sub Tropical Dry Settlement on Hills"),
    "wte_278": tr_layers.tr("Sub Tropical Dry Cropland on Hills"),
    "wte_279": tr_layers.tr("Sub Tropical Dry Grassland on Hills"),
    "wte_280": tr_layers.tr("Cool Temperate Desert Forest on Mountains"),
    "wte_281": tr_layers.tr("Sub Tropical Dry Sparsley or Non vegetated on Hills"),
    "wte_282": tr_layers.tr("Sub Tropical Dry Cropland on Plains"),
    "wte_283": tr_layers.tr("Sub Tropical Dry Sparsley or Non vegetated on Plains"),
    "wte_284": tr_layers.tr("Sub Tropical Dry Shrubland on Plains"),
    "wte_285": tr_layers.tr("Sub Tropical Dry Shrubland on Hills"),
    "wte_286": tr_layers.tr("Sub Tropical Dry Shrubland on Mountains"),
    "wte_287": tr_layers.tr("Sub Tropical Dry Cropland on Tablelands"),
    "wte_288": tr_layers.tr("Sub Tropical Dry Forest on Plains"),
    "wte_289": tr_layers.tr("Sub Tropical Dry Grassland on Plains"),
    "wte_290": tr_layers.tr("Sub Tropical Dry Forest on Hills"),
    "wte_291": tr_layers.tr("Sub Tropical Dry Sparsley or Non vegetated on Tablelands"),
    "wte_292": tr_layers.tr("Polar Desert Cropland on Mountains"),
    "wte_293": tr_layers.tr("Sub Tropical Dry Shrubland on Tablelands"),
    "wte_294": tr_layers.tr("Sub Tropical Dry Forest on Tablelands"),
    "wte_295": tr_layers.tr("Sub Tropical Moist Grassland on Hills"),
    "wte_296": tr_layers.tr("Sub Tropical Dry Settlement on Tablelands"),
    "wte_297": tr_layers.tr("Sub Tropical Moist Cropland on Plains"),
    "wte_298": tr_layers.tr("Sub Tropical Dry Grassland on Tablelands"),
    "wte_299": tr_layers.tr("Sub Tropical Moist Sparsley or Non vegetated on Plains"),
    "wte_300": tr_layers.tr("Sub Tropical Moist Shrubland on Plains"),
    "wte_301": tr_layers.tr("Sub Tropical Moist Forest on Plains"),
    "wte_302": tr_layers.tr("Sub Tropical Moist Cropland on Tablelands"),
    "wte_303": tr_layers.tr("Sub Tropical Moist Forest on Tablelands"),
    "wte_304": tr_layers.tr("Sub Tropical Moist Grassland on Tablelands"),
    "wte_305": tr_layers.tr("Sub Tropical Moist Shrubland on Tablelands"),
    "wte_306": tr_layers.tr("Polar Desert Sparsley or Non vegetated on Mountains"),
    "wte_307": tr_layers.tr("Sub Tropical Moist Shrubland on Hills"),
    "wte_308": tr_layers.tr("Sub Tropical Moist Settlement on Plains"),
    "wte_309": tr_layers.tr("Polar Desert Forest on Mountains"),
    "wte_310": tr_layers.tr("Sub Tropical Desert Shrubland on Mountains"),
    "wte_311": tr_layers.tr("Sub Tropical Moist Grassland on Plains"),
    "wte_312": tr_layers.tr("Sub Tropical Desert Sparsley or Non vegetated on Mountains"),
    "wte_313": tr_layers.tr("Sub Tropical Desert Shrubland on Plains"),
    "wte_314": tr_layers.tr("Sub Tropical Desert Sparsley or Non vegetated on Plains"),
    "wte_315": tr_layers.tr("Cool Temperate Desert Snow and Ice on Mountains"),
    "wte_316": tr_layers.tr("Sub Tropical Moist Sparsley or Non vegetated on Tablelands"),
    "wte_317": tr_layers.tr("Boreal Desert Forest on Mountains"),
    "wte_318": tr_layers.tr("Polar Dry Settlement on Tablelands"),
    "wte_319": tr_layers.tr("Polar Dry Settlement on Hills"),
    "wte_320": tr_layers.tr("Sub Tropical Desert Grassland on Mountains"),
    "wte_321": tr_layers.tr("Polar Desert Snow and Ice on Mountains"),
    "wte_322": tr_layers.tr("Sub Tropical Desert Grassland on Plains"),
    "wte_323": tr_layers.tr("Boreal Desert Shrubland on Mountains"),
    "wte_324": tr_layers.tr("Polar Desert Shrubland on Mountains"),
    "wte_325": tr_layers.tr("Boreal Desert Settlement on Mountains"),
    "wte_326": tr_layers.tr("Boreal Desert Sparsley or Non vegetated on Plains"),
    "wte_327": tr_layers.tr("Sub Tropical Desert Forest on Mountains"),
    "wte_328": tr_layers.tr("Sub Tropical Desert Forest on Plains"),
    "wte_329": tr_layers.tr("Sub Tropical Desert Shrubland on Tablelands"),
    "wte_330": tr_layers.tr("Sub Tropical Desert Settlement on Plains"),
    "wte_331": tr_layers.tr("Sub Tropical Desert Shrubland on Hills"),
    "wte_332": tr_layers.tr("Tropical Dry Sparsley or Non vegetated on Plains"),
    "wte_333": tr_layers.tr("Tropical Dry Cropland on Plains"),
    "wte_334": tr_layers.tr("Tropical Dry Sparsley or Non vegetated on Hills"),
    "wte_335": tr_layers.tr("Tropical Dry Shrubland on Hills"),
    "wte_336": tr_layers.tr("Tropical Dry Cropland on Hills"),
    "wte_337": tr_layers.tr("Tropical Dry Settlement on Hills"),
    "wte_338": tr_layers.tr("Tropical Dry Cropland on Mountains"),
    "wte_339": tr_layers.tr("Tropical Dry Sparsley or Non vegetated on Mountains"),
    "wte_340": tr_layers.tr("Sub Tropical Desert Sparsley or Non vegetated on Hills"),
    "wte_341": tr_layers.tr("Tropical Dry Shrubland on Plains"),
    "wte_342": tr_layers.tr("Tropical Dry Shrubland on Mountains"),
    "wte_343": tr_layers.tr("Tropical Dry Settlement on Plains"),
    "wte_344": tr_layers.tr("Tropical Dry Grassland on Mountains"),
    "wte_345": tr_layers.tr("Tropical Dry Settlement on Mountains"),
    "wte_346": tr_layers.tr("Sub Tropical Desert Cropland on Plains"),
    "wte_347": tr_layers.tr("Sub Tropical Desert Sparsley or Non vegetated on Tablelands"),
    "wte_348": tr_layers.tr("Sub Tropical Moist Settlement on Tablelands"),
    "wte_349": tr_layers.tr("Sub Tropical Desert Cropland on Hills"),
    "wte_350": tr_layers.tr("Sub Tropical Desert Cropland on Mountains"),
    "wte_351": tr_layers.tr("Sub Tropical Desert Settlement on Mountains"),
    "wte_352": tr_layers.tr("Sub Tropical Desert Grassland on Hills"),
    "wte_353": tr_layers.tr("Sub Tropical Desert Forest on Hills"),
    "wte_354": tr_layers.tr("Sub Tropical Desert Settlement on Hills"),
    "wte_355": tr_layers.tr("Sub Tropical Desert Cropland on Tablelands"),
    "wte_356": tr_layers.tr("Tropical Dry Sparsley or Non vegetated on Tablelands"),
    "wte_357": tr_layers.tr("Sub Tropical Desert Settlement on Tablelands"),
    "wte_358": tr_layers.tr("Tropical Dry Cropland on Tablelands"),
    "wte_359": tr_layers.tr("Tropical Dry Grassland on Hills"),
    "wte_360": tr_layers.tr("Tropical Dry Grassland on Plains"),
    "wte_361": tr_layers.tr("Tropical Dry Forest on Plains"),
    "wte_362": tr_layers.tr("Tropical Desert Sparsley or Non vegetated on Plains"),
    "wte_363": tr_layers.tr("Tropical Dry Forest on Hills"),
    "wte_364": tr_layers.tr("Tropical Dry Shrubland on Tablelands"),
    "wte_365": tr_layers.tr("Tropical Dry Forest on Mountains"),
    "wte_366": tr_layers.tr("Sub Tropical Desert Grassland on Tablelands"),
    "wte_367": tr_layers.tr("Tropical Desert Cropland on Plains"),
    "wte_368": tr_layers.tr("Tropical Dry Settlement on Tablelands"),
    "wte_369": tr_layers.tr("Tropical Desert Sparsley or Non vegetated on Mountains"),
    "wte_370": tr_layers.tr("Tropical Desert Grassland on Plains"),
    "wte_371": tr_layers.tr("Tropical Desert Grassland on Mountains"),
    "wte_372": tr_layers.tr("Tropical Desert Cropland on Mountains"),
    "wte_373": tr_layers.tr("Tropical Desert Shrubland on Plains"),
    "wte_374": tr_layers.tr("Tropical Desert Sparsley or Non vegetated on Hills"),
    "wte_375": tr_layers.tr("Tropical Desert Sparsley or Non vegetated on Tablelands"),
    "wte_376": tr_layers.tr("Tropical Desert Shrubland on Mountains"),
    "wte_377": tr_layers.tr("Tropical Desert Settlement on Mountains"),
    "wte_378": tr_layers.tr("Tropical Desert Settlement on Plains"),
    "wte_379": tr_layers.tr("Tropical Desert Forest on Plains"),
    "wte_380": tr_layers.tr("Tropical Desert Cropland on Hills"),
    "wte_381": tr_layers.tr("Tropical Desert Settlement on Hills"),
    "wte_382": tr_layers.tr("Tropical Dry Grassland on Tablelands"),
    "wte_383": tr_layers.tr("Tropical Desert Grassland on Hills"),
    "wte_384": tr_layers.tr("Tropical Desert Settlement on Tablelands"),
    "wte_385": tr_layers.tr("Tropical Desert Cropland on Tablelands"),
    "wte_386": tr_layers.tr("Tropical Desert Shrubland on Hills"),
    "wte_387": tr_layers.tr("Tropical Moist Cropland on Plains"),
    "wte_388": tr_layers.tr("Tropical Moist Settlement on Plains"),
    "wte_389": tr_layers.tr("Tropical Moist Forest on Plains"),
    "wte_390": tr_layers.tr("Tropical Moist Cropland on Hills"),
    "wte_391": tr_layers.tr("Tropical Moist Cropland on Mountains"),
    "wte_392": tr_layers.tr("Tropical Moist Forest on Mountains"),
    "wte_393": tr_layers.tr("Tropical Moist Grassland on Plains"),
    "wte_394": tr_layers.tr("Tropical Dry Forest on Tablelands"),
    "wte_395": tr_layers.tr("Tropical Moist Sparsley or Non vegetated on Plains"),
    "wte_396": tr_layers.tr("Tropical Moist Shrubland on Plains"),
    "wte_397": tr_layers.tr("Tropical Desert Grassland on Tablelands"),
    "wte_398": tr_layers.tr("Tropical Moist Forest on Hills"),
    "wte_399": tr_layers.tr("Warm Temperate Moist Snow and Ice on Mountains"),
    "wte_400": tr_layers.tr("Sub Tropical Desert Forest on Tablelands"),
    "wte_401": tr_layers.tr("Tropical Moist Grassland on Mountains"),
    "wte_402": tr_layers.tr("Tropical Moist Sparsley or Non vegetated on Mountains"),
    "wte_403": tr_layers.tr("Tropical Moist Grassland on Hills"),
    "wte_404": tr_layers.tr("Tropical Moist Shrubland on Mountains"),
    "wte_405": tr_layers.tr("Tropical Moist Settlement on Mountains"),
    "wte_406": tr_layers.tr("Tropical Desert Forest on Hills"),
    "wte_407": tr_layers.tr("Tropical Moist Settlement on Hills"),
    "wte_408": tr_layers.tr("Tropical Moist Shrubland on Hills"),
    "wte_409": tr_layers.tr("Tropical Moist Forest on Tablelands"),
    "wte_410": tr_layers.tr("Tropical Moist Shrubland on Tablelands"),
    "wte_411": tr_layers.tr("Tropical Moist Cropland on Tablelands"),
    "wte_412": tr_layers.tr("Tropical Desert Shrubland on Tablelands"),
    "wte_413": tr_layers.tr("Tropical Moist Settlement on Tablelands"),
    "wte_414": tr_layers.tr("Tropical Moist Grassland on Tablelands"),
    "wte_415": tr_layers.tr("Tropical Moist Sparsley or Non vegetated on Hills"),
    "wte_416": tr_layers.tr("Tropical Moist Sparsley or Non vegetated on Tablelands"),
    "wte_417": tr_layers.tr("Tropical Desert Forest on Mountains"),
    "wte_418": tr_layers.tr("Tropical Desert Forest on Tablelands"),
    "wte_419": tr_layers.tr("Warm Temperate Dry Snow and Ice on Mountains"),
    "wte_420": tr_layers.tr("Cool Temperate Dry Snow and Ice on Plains"),
    "wte_421": tr_layers.tr("Polar Desert Sparsley or Non vegetated on Tablelands"),
    "wte_422": tr_layers.tr("Polar Desert Settlement on Tablelands"),
    "wte_423": tr_layers.tr("Polar Desert Shrubland on Tablelands"),
    "wte_424": tr_layers.tr("Polar Desert Sparsley or Non vegetated on Plains"),
    "wte_425": tr_layers.tr("Polar Desert Shrubland on Plains"),
    "wte_426": tr_layers.tr("Polar Desert Cropland on Plains"),
    "wte_427": tr_layers.tr("Polar Desert Forest on Plains"),
    "wte_428": tr_layers.tr("Polar Desert Settlement on Mountains"),
    "wte_429": tr_layers.tr("Warm Temperate Desert Forest on Tablelands"),
    "wte_430": tr_layers.tr("Polar Desert Grassland on Tablelands"),
    "wte_431": tr_layers.tr("Polar Desert Grassland on Plains"),
}
