name: Build documentation PDFs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'tasks.py'
      - 'requirements-dev.txt'
      - 'LDMP/metadata.txt'
      - '.readthedocs.yaml'
      - '.github/workflows/build_docs_pdfs.yaml'

permissions:
  contents: read
  id-token: write

jobs:
  build_docs_pdfs:
    name: Build documentation PDFs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Setup Python environment
        uses: ./.github/actions/setup-python-env
      - name: Install Playwright Chromium
        run: python -m playwright install --with-deps chromium
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - name: Docs pre-build
        run: invoke rtd-pre-build
      - name: Build PDF and push to S3
        run: invoke docs-build --pdf --upload
