name: Create plugin package in the PR

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  create-package:
    runs-on: ubuntu-22.04
    container:
      image: qgis/qgis:release-3_34
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix Python command
        run: apt-get update && apt-get install -y python-is-python3

      - name: Install git and configure
        run: |
          apt-get update && apt-get install -y git
          git config --global --add safe.directory /__w/trends.earth/trends.earth
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip tooling
        run: |
          python -m pip --version
          python -m pip install --upgrade pip setuptools wheel build

      - name: Install plugin dependencies
        env:
          PIP_ALWAYS_USE_PEP517: '1'
        run: |
          pip install --no-cache-dir -r requirements-dev.txt
          pip install --no-cache-dir -r requirements.txt

      - name: Verify te_algorithms import
        run: |
          python - <<'PY'
          import sys
          try:
              import te_algorithms
              print('te_algorithms imported, version:', getattr(te_algorithms, '__version__', 'unknown'))
          except Exception as e:
              print('Failed to import te_algorithms:', e)
              sys.exit(1)
          PY

      - name: Get unique identifier
        id: get-identifier
        run: |
          echo "PACKAGE_ID=$(python -c "import uuid; print(str(uuid.uuid4())[:4])")" >> $GITHUB_ENV

      - name: Set version SHA
        run: invoke set-version

      - name: Build zipfile
        shell: bash
        run: |
          SAFE_REF_NAME="${{ github.event.pull_request.head.ref }}"
          SAFE_REF_NAME="${SAFE_REF_NAME//\//_}"
          invoke zipfile-build  --filename LDMP-${SAFE_REF_NAME}_${{ env.PACKAGE_ID }}.zip
          echo "REF_NAME=${SAFE_REF_NAME}" >> $GITHUB_ENV

      - name: Plugin path details
        id: get-zip-details
        run: |
          ls
          
          unzip -o $GITHUB_WORKSPACE/LDMP-"$REF_NAME"_"$PACKAGE_ID".zip -d build
          
          mkdir build/LDMP-"$REF_NAME"_"$PACKAGE_ID"
          
          mv build/LDMP build/LDMP-"$REF_NAME"_"$PACKAGE_ID/LDMP"

          echo "ZIP_PATH=$GITHUB_WORKSPACE/build/LDMP-"$REF_NAME"_"$PACKAGE_ID"" >> $GITHUB_ENV
          echo "ZIP_NAME=LDMP-"$REF_NAME"_"$PACKAGE_ID"">> $GITHUB_ENV

      - name: Uploading plugin build
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}
          path: ${{ env.ZIP_PATH }}

      - name: Save the artifact url and pull request number
        shell: bash
        env:
          PR_NUMBER: ${{ github.event.number }}
          ARTIFACT_URL: ${{ steps.artifact-upload-step.outputs.artifact-url }}
        run: |
          echo $ARTIFACT_URL > artifact_url.txt
          echo $PR_NUMBER > pr_number.txt

      - name: Upload the artifact url
        uses: actions/upload-artifact@v4
        with:
          name: artifact_url
          path: ./artifact_url.txt

      - name: Upload the PR number
        uses: actions/upload-artifact@v4
        with:
          name: pr_number
          path: ./pr_number.txt
