name: Update the staging repository with a new plugin version
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  staging_repository_update:
    name: Staging repository update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Fetch all history including tags for setuptools-scm
          fetch-tags: true

      - name: Build plugin ZIP
        uses: ./.github/actions/build-plugin-zip
        with:
          filename: LDMP.zip

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: release
          clean: false
          fetch-depth: 0  # Fetch all history including tags for setuptools-scm

      - name: Make directory
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          
          echo "REF_NAME=$REF_NAME" >> $GITHUB_ENV
          mkdir -p $GITHUB_WORKSPACE/docs/repository/$REF_NAME

      - name: Update custom plugin repository to include latest plugin version
        env:
          REF_NAME: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp $GITHUB_WORKSPACE/LDMP.zip $GITHUB_WORKSPACE/docs/repository/$REF_NAME/LDMP.zip

          DOWNLOAD_URL="https://raw.githubusercontent.com/ConservationInternational/trends.earth/refs/heads/release/docs/repository/$REF_NAME/LDMP.zip"
          echo "$DOWNLOAD_URL"

          invoke generate-plugin-repo-xml \
            --prerelease \
            --prerelease-url "$DOWNLOAD_URL" \
            --prerelease-time "$(date +'%Y-%m-%dT%H:%M:%SZ')" \
            --prerelease-filename "LDMP.zip"

          echo " " >> docs/repository/plugins.xml

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory $GITHUB_WORKSPACE

          git add docs/repository
          git add -f docs/repository/$REF_NAME/LDMP.zip
          git commit -m "Update on the staging repository"
          git push origin release
