name: Updating staging with a new released plugin
on:
  release:
    types:
      - published
      - edited

permissions:
  contents: write

jobs:
  update-staging:
    runs-on: ubuntu-22.04
    container:
      image: qgis/qgis:release-3_34
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Fetch all history including tags for setuptools-scm

      - name: Setup QGIS environment
        uses: ./.github/actions/setup-qgis-env

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: release
          fetch-depth: 0  # Fetch all history including tags for setuptools-scm
      - name: Update custom plugin repository to include latest plugin releases
        run: |
          invoke generate-plugin-repo-xml
          echo " " >> docs/repository/plugins.xml 
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory /__w/trends.earth/trends.earth

          git add -A
          git commit -m "Update on plugins.xml"
          git push origin release
