name: Update translations

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/translation_update.yaml
  schedule:
    - cron: "0 4 * * 1,3,5"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  translation_update:
    if: ${{ github.ref_name == 'main' }}
    name: Update translations from transifex
    runs-on: ubuntu-latest
    env:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}
      TX_HOSTNAME: ${{ secrets.TX_HOSTNAME }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Install Qt tools (lrelease and pylupdate5)
        run: sudo apt-get update && sudo apt-get install -y qttools5-dev-tools pyqt5-dev-tools
      - name: Setup Python environment
        uses: ./.github/actions/setup-python-env
      - name: Install transifex CLI
        run: |
          curl -fsSL -L -o tx.tar.gz https://github.com/transifex/cli/releases/latest/download/tx-linux-amd64.tar.gz
          tar xzf tx.tar.gz tx
          chmod +x tx
          rm tx.tar.gz
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Pull updated strings from transifex
        run: invoke translate-pull --force
      - name: Push strings to transifex
        run: invoke translate-push
      - name: Create pull request
        uses: ./.github/actions/create-automated-pr
        with:
          commit-message: Update translations
          branch: translation-updates
          title: "Update translations"
          body: |
            Refresh translations
          labels: |
            i18n
            automated pr
          add-paths: |
            docs/i18n/**/*.po
            docs/source/for_users/downloads/index.md
            docs/source/for_developers/changelog.rst
            LDMP/i18n/*.ts
