name: Update downloads page

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  build-download-page:
    if: ${{ github.ref_name == 'main' }}
    name: Rebuild downloads page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Python environment
        uses: ./.github/actions/setup-python-env
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - name: Build downloads page
        run: invoke build-download-page
      - name: Create pull request
        uses: ./.github/actions/create-automated-pr
        with:
          commit-message: Update downloads page
          branch: automation/update-downloads-page
          title: "Update downloads page"
          body: |
            Refresh downloads page content from nightly automation.
          labels: |
            automated pr
            documentation
          add-paths: |
            docs/source/for_users/downloads/index.md
